FROM python:3.8

WORKDIR /app

RUN python -m pip install --upgrade pip

RUN pip install Cython==0.29.21 uvicorn

EXPOSE 8000

CMD pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000
