# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_subvin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'test_groups',
            },
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RenameModel(old_name='TestCategories', new_name='TestCategory'),
        migrations.AlterField(
            model_name='test',
            name='test_categories',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.TestCategory'
            ),
        ),
        migrations.RenameField(
            model_name='test', old_name='test_categories', new_name='test_category'
        ),
        migrations.AddField(
            model_name='testcategory',
            name='test_group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.TestGroup',
            ),
        ),
    ]
