# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_auto_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleVersionNodeNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('node_id', models.IntegerField()),
                ('notes', models.TextField()),
                (
                    'rule_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='app.RuleVersion',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
                ),
            ],
            options={
                'db_table': 'rule_version_node_notes',
            },
        ),
    ]
