# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintests',
            name='qualifier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
