# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_auto_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintests',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
