# Generated by Django 3.1 on 2021-04-05 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0012_auto_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcategory',
            name='test_group',
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='TestGroup',
        ),
        migrations.RemoveField(
            model_name='test',
            name='type',
        ),
    ]
