# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0013_auto_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintests',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
